# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2cc14af737b92bd098c48efbd428b7af70fc7d65a5a51cb08ce9e8165e756a8a3659782f6056bd8627fbface048e944f618122faa8274bb57436f21e08af0e3

test:
  secret_key_base: fdb6ebd9393d2d437f390c7d4841ddfe3128b432a4acfe2554b47317d9f1fffc64d5fa045d8442cc00eec92fbe15a16568aff7802af5d5a9c4518fe81dbcb508

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
